using System;

namespace System.GAC
{
	public enum IASSEMBLYCACHE_UNINSTALL_DISPOSITION
	{
		IASSEMBLYCACHE_UNINSTALL_DISPOSITION_UNINSTALLED = 1,
		IASSEMBLYCACHE_UNINSTALL_DISPOSITION_STILL_IN_USE = 2,
		IASSEMBLYCACHE_UNINSTALL_DISPOSITION_ALREADY_UNINSTALLED = 3,
		IASSEMBLYCACHE_UNINSTALL_DISPOSITION_DELETE_PENDING = 4,
		IASSEMBLYCACHE_UNINSTALL_DISPOSITION_HAS_INSTALL_REFERENCES = 5,
		IASSEMBLYCACHE_UNINSTALL_DISPOSITION_REFERENCE_NOT_FOUND = 6
	}
}